spring:
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${db.username:postgres}
    password: ${db.password:postgres}
  #jpa:
    #hibernate.ddl-auto: validate
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: create
jwt:
  secret: SECRET
  expiration-time: 3600000
